### PR TITLE
fix float input

### PR DESCRIPTION
**Pull request by itsmohamedyahia**
if input is null or a float, i defaulted to 0

### CODE REVIEW

**Comment by jtweeder** [comment]
Hey @itsmohamedyahia , thanks for the PR and contribution.  Testing out this proposed fix, and there is a couple of issues, I think some modifications will fix up.

1.  Dont need to check for presence of float, the allowed input is only integer so if the user tries 1.2 or any other float then the page prompts them to fix that input.  
2. The blank/deleted input issue actually throws a ` ValueError: invalid literal for int() with base 10: '' ` So really just need to check for that `''` as the input and if that is the case change it to 0.

From some feature additions I just finished, I added a helper function that I think will help with this.  See if you can use it for your solution.

See its usage in:
https://github.com/jtweeder/mealcurator/blob/b7d526fbe3e839a1e47f4d58c7b5613879d8064c/stewpot/views.py#L25

**Review by jtweeder — CHANGES_REQUESTED** [review]
See PR Conversation comments for comments (sorry, I should have put them here instead).

**Comment by itsmohamedyahia** [comment]
Hey @jtweeder, thanks for bringing these issues to my attention. I have applied the modifications using that helper function you provided.  Let me know if you have any other feedback or if there are any other issues that you would like me to address.

**Review by jtweeder — CHANGES_REQUESTED** [review]
Similar to how the helper function is imported in the example code it needs to be imported in both of these sets of code before it will be available for use.

**Comment by itsmohamedyahia** [comment]
Sorry for this silly mistake. I imported the function in both sets as required.

**Review by jtweeder — APPROVED** [review]

**Comment by jtweeder** [comment]
Fixes #47

**Pull request merged**
